---
- name: Define variables.
  set_fact:
    deploy_project_link_shared_task: "{{ __deploy_project_link_shared_task }}"
  when: deploy_project_link_shared_task is not defined

- include: register_variables.yml
- include: handle_previous.yml
- include: pull_repository.yml
- include: templated_files.yml
- include: "{{deploy_project_link_shared_task}}"
- include: ensure_writables.yml