---
- name: Pull sources from the repository.
  git:
    repo={{deploy.project.repo}}
    dest={{deploy.project.root}}/shared/cached-copy
    version={{deploy.project.branch}}
    accept_hostkey=yes
  when: deploy.project.scm == "git"

- name: Copying from local source
  synchronize:
    src: "{{deploy.project.source}}"
    dest: "{{deploy.project.root}}/shared/cached-copy"
    owner: no
    group: no
    delete: yes
    rsync_opts: "{{ deploy.project.rsync_opts }}"
  when: deploy.project.scm == "rsync"

- name: Copying archive from local source
  file:
    path: "{{deploy.project.root}}/shared/cached-copy"
    state: directory
    recurse: yes
  when: deploy.project.scm == "archive"

- name: Copying archive from local source
  unarchive:
    src: "{{deploy.project.source}}"
    dest: "{{deploy.project.root}}/shared/cached-copy"
    remote_src: False
  when: deploy.project.scm == "archive"

- name: Create release directory
  command: mv {{deploy.project.root}}/shared/cached-copy {{deploy.project.root}}/releases/{{next_release}}
  args:
    chdir: "{{deploy.project.root}}/shared"
